[fio toup] ostree_object: Add missing list include
| aktualizr/src/sota_tools/ostree_object.h:75:26: error: ‘list’ in namespace ‘std’ does not name a template type
|    75 |   using childiter = std::list<OSTreeObject::ptr>::iterator;
|       |                          ^~~~
| aktualizr/src/sota_tools/ostree_object.h:12:1: note: ‘std::list’ is defined in header ‘<list>’; did you forget to ‘#include <list>’?

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>